"use client";

import Image from "next/image";
import { useCallback, useState } from "react";
import type { ProjectScreenshot } from "@/data/projects";
import ScreenshotLightbox from "./ScreenshotLightbox";

function BrowserFrame({ screenshot, onOpen, primary = false }: { screenshot: ProjectScreenshot; onOpen: () => void; primary?: boolean }) {
  return <figure><button onClick={onOpen} className="group block w-full overflow-hidden rounded-lg border border-white/10 bg-[#111418] text-left transition hover:border-white/25" aria-label={`Expand ${screenshot.label} screenshot`}><span className="flex h-7 items-center gap-1.5 border-b border-white/10 px-3" aria-hidden="true"><i className="h-1.5 w-1.5 rounded-full bg-zinc-700"/><i className="h-1.5 w-1.5 rounded-full bg-zinc-700"/><i className="h-1.5 w-1.5 rounded-full bg-zinc-700"/></span><span className={`relative block ${primary ? "aspect-[1.6]" : "aspect-[1.6]"}`}><Image src={screenshot.src} alt={screenshot.alt} fill sizes={primary ? "(min-width: 768px) 50vw, 85vw" : "(min-width: 768px) 25vw, 85vw"} className="object-contain transition duration-300 group-hover:scale-[1.01]"/></span></button><figcaption className="mt-2 font-mono text-[10px] uppercase tracking-wider text-zinc-600">{screenshot.label}</figcaption></figure>;
}

export default function ProjectGallery({ screenshots, variant }: { screenshots: ProjectScreenshot[]; variant: "salony" | "browser" }) {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  const close = useCallback(() => setActiveIndex(null), []);
  const change = useCallback((index: number) => setActiveIndex(index), []);

  if (variant === "salony") return <><div className="md:hidden"><div className="flex snap-x snap-mandatory gap-4 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{screenshots.map((shot,index)=><figure key={shot.src} className="w-[78vw] max-w-[310px] shrink-0 snap-center"><button onClick={()=>setActiveIndex(index)} className="relative block aspect-[.49] w-full overflow-hidden rounded-[1.6rem] border border-white/15 bg-black"><Image src={shot.src} alt={shot.alt} fill sizes="78vw" className="object-contain"/></button><figcaption className="mt-3 text-center font-mono text-[10px] uppercase tracking-wider text-zinc-500">{shot.label}</figcaption></figure>)}</div></div><div className="relative hidden min-h-[570px] items-center justify-center overflow-hidden md:flex"><div className="absolute left-[4%] top-[14%] z-10 w-[27%] -rotate-3"><Phone shot={screenshots[1]} onOpen={()=>setActiveIndex(1)}/></div><div className="absolute right-[4%] top-[14%] z-10 w-[27%] rotate-3"><Phone shot={screenshots[2]} onOpen={()=>setActiveIndex(2)}/></div><div className="relative z-20 w-[31%]"><Phone shot={screenshots[0]} onOpen={()=>setActiveIndex(0)}/></div><button onClick={()=>setActiveIndex(3)} className="absolute bottom-5 left-[7%] z-30 w-[18%] overflow-hidden rounded-xl border border-white/15 opacity-80 transition hover:opacity-100"><span className="relative block aspect-[.49]"><Image src={screenshots[3].src} alt={screenshots[3].alt} fill sizes="18vw" className="object-contain"/></span></button><button onClick={()=>setActiveIndex(4)} className="absolute bottom-5 right-[7%] z-30 w-[18%] overflow-hidden rounded-xl border border-white/15 opacity-80 transition hover:opacity-100"><span className="relative block aspect-[.49]"><Image src={screenshots[4].src} alt={screenshots[4].alt} fill sizes="18vw" className="object-contain"/></span></button></div><ScreenshotLightbox screenshots={screenshots} activeIndex={activeIndex} onClose={close} onChange={change}/></>;

  return <><div className="md:hidden"><div className="flex snap-x snap-mandatory gap-4 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{screenshots.map((shot,index)=><div key={shot.src} className="w-[84vw] max-w-[520px] shrink-0 snap-center"><BrowserFrame screenshot={shot} onOpen={()=>setActiveIndex(index)} primary/></div>)}</div></div><div className="hidden md:block"><BrowserFrame screenshot={screenshots[0]} onOpen={()=>setActiveIndex(0)} primary/><div className="mt-4 grid grid-cols-2 gap-4">{screenshots.slice(1).map((shot,index)=><BrowserFrame key={shot.src} screenshot={shot} onOpen={()=>setActiveIndex(index+1)}/>)}</div></div><ScreenshotLightbox screenshots={screenshots} activeIndex={activeIndex} onClose={close} onChange={change}/></>;
}

function Phone({ shot, onOpen }: { shot: ProjectScreenshot; onOpen: () => void }) { return <button onClick={onOpen} className="group relative block aspect-[.49] w-full overflow-hidden rounded-[1.7rem] border-[5px] border-[#202327] bg-black shadow-2xl transition hover:-translate-y-1" aria-label={`Expand ${shot.label} screenshot`}><Image src={shot.src} alt={shot.alt} fill sizes="31vw" className="object-contain"/></button>; }
